seed_everything: 7
trainer:
  checkpoint_callback: true
  logger:
    - class_path: pytorch_lightning.loggers.CSVLogger
      init_args:
        save_dir: "logs/"
        name: "crohme_training"
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    # Best Model (Based on val_ExpRate)
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: "checkpoints2/best"
        save_top_k: 1
        monitor: val_ExpRate
        mode: max
        filename: '{epoch}-{step}-{val_ExpRate:.4f}'
    # Latest Model (Saved Every Epoch)
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: "checkpoints2/latest"  # Folder for latest models
        save_top_k: 1                  # Keep only the latest checkpoint
        every_n_epochs: 10             # Save every 10 epoch
        filename: "latest-{epoch}"
  gpus: 1
  check_val_every_n_epoch: 2
  max_epochs: 400
  deterministic: true
model:
  d_model: 256
  # encoder
  growth_rate: 24
  num_layers: 16
  # decoder
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dc: 32
  dropout: 0.3
  vocab_size: 113  # 110 + 3
  cross_coverage: true
  self_coverage: true
  # beam search
  beam_size: 10
  max_len: 200
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  # training
  learning_rate: 1.0
  patience: 20
  milestones:
    - 300
    - 350
data:
  folder: data/crohme
  test_folder: 2014
  max_size: 320000
  scale_to_limit: true
  train_batch_size: 8
  eval_batch_size: 4
  num_workers: 8
  scale_aug: false